version: '3.8'

# GPU 없이 테스트용 - Mock LLM 서비스 사용
# 사용법: docker-compose -f docker-compose.test.yml up --build

services:
  postgres:
    image: postgres:15
    container_name: llm-webapp-postgres-test
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-llm_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-llm_webapp}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-llm_app}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: llm-webapp-backend-test
    environment:
      USE_SQLITE: "false"
      POSTGRES_USER: ${POSTGRES_USER:-llm_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-llm_webapp}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      SESSION_TIMEOUT_MINUTES: ${SESSION_TIMEOUT_MINUTES:-30}
      HF_MODEL_NAME: ${HF_MODEL_NAME:-Qwen/Qwen2.5-1.5B-Instruct}
      HF_HOME: /app/.cache/huggingface
      TRANSFORMERS_CACHE: /app/.cache/huggingface
      PER_USER_QUOTA_GB: ${PER_USER_QUOTA_GB:-10}
      TOTAL_STORAGE_CAPACITY_GB: ${TOTAL_STORAGE_CAPACITY_GB:-500}
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/scripts:/app/scripts
      - uploads_test_data:/uploads
      - hf_cache:/app/.cache/huggingface
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for postgres...' &&
        sleep 5 &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Creating initial admin user...' &&
        python scripts/create_admin.py --username admin --password admin123! 2>/dev/null || true &&
        echo 'Starting backend server...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: llm-webapp-frontend-test
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_test_data:
  uploads_test_data:
  hf_cache:

networks:
  default:
    name: llm-webapp-test-network
