"""Add missing tables (Admin, SafetyFilterRule, etc)

Revision ID: f4412ac279b2
Revises: 004
Create Date: 2025-11-01 16:13:44.000739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4412ac279b2'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('filter_type', sa.String(length=20), nullable=False),
    sa.Column('filter_phase', sa.String(length=10), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('matched_keyword', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('bypass_attempted', sa.Boolean(), nullable=False),
    sa.Column('bypass_succeeded', sa.Boolean(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_events_category'), 'filter_events', ['category'], unique=False)
    op.create_index(op.f('ix_filter_events_conversation_id'), 'filter_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_filter_events_created_at'), 'filter_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_filter_events_user_id'), 'filter_events', ['user_id'], unique=False)
    op.create_table('safety_filter_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('VIOLENCE', 'SEXUAL', 'DANGEROUS', 'HATE', 'PII', name='filtercategory'), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('regex_patterns', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('replacement_text', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_rule', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_filter_rules_category'), 'safety_filter_rules', ['category'], unique=False)
    op.create_index(op.f('ix_safety_filter_rules_is_active'), 'safety_filter_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_safety_filter_rules_name'), 'safety_filter_rules', ['name'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_tool', sa.Boolean(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('avg_execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_category'), 'tools', ['category'], unique=False)
    op.create_index(op.f('ix_tools_is_active'), 'tools', ['is_active'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_view_logs', sa.Boolean(), nullable=False),
    sa.Column('can_modify_settings', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tool_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('agent_iteration', sa.Integer(), nullable=True),
    sa.Column('thought', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('timeout_occurred', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_conversation_id'), 'tool_executions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_created_at'), 'tool_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_executions_success'), 'tool_executions', ['success'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_id'), 'tool_executions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_user_id'), 'tool_executions', ['user_id'], unique=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               comment='Document owner (redundant for isolation checks)',
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes (max 50MB)',
               existing_nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='pdf, docx, txt',
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_processing_time'), table_name='messages')
    op.drop_constraint(op.f('sessions_session_token_key'), 'sessions', type_='unique')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=False)
    op.create_unique_constraint(op.f('sessions_session_token_key'), 'sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_messages_processing_time'), 'messages', ['processing_time_ms'], unique=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pdf, docx, txt',
               existing_nullable=False)
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes (max 50MB)',
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Document owner (redundant for isolation checks)',
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_tool_executions_user_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_tool_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_success'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_created_at'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_conversation_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_table('admins')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_is_active'), table_name='tools')
    op.drop_index(op.f('ix_tools_category'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_safety_filter_rules_name'), table_name='safety_filter_rules')
    op.drop_index(op.f('ix_safety_filter_rules_is_active'), table_name='safety_filter_rules')
    op.drop_index(op.f('ix_safety_filter_rules_category'), table_name='safety_filter_rules')
    op.drop_table('safety_filter_rules')
    op.drop_index(op.f('ix_filter_events_user_id'), table_name='filter_events')
    op.drop_index(op.f('ix_filter_events_created_at'), table_name='filter_events')
    op.drop_index(op.f('ix_filter_events_conversation_id'), table_name='filter_events')
    op.drop_index(op.f('ix_filter_events_category'), table_name='filter_events')
    op.drop_table('filter_events')
    # ### end Alembic commands ###
